name: aiopusher

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  aiopusher:
    runs-on: nix

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Run AioPusher
        run: nix run .#workflows.aiopusher
