name: "bumper"

on:
  workflow_dispatch:
  pull_request_target:
    branches:
      - "master"

jobs:
  bumper:
    runs-on: nix

    permissions:
      contents: "write"

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Run Bumper
        run: nix run .#workflows.aiopusher
